apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      ## Active Service Name
      activeService: rollout-bluegreen-active
      ## Preview Service Name
      previewService: rollout-bluegreen-preview
      ## Manual Update?
      # autoPromotionEnabled: false
      autoPromotionEnabled: true
      previewReplicaCount: 1
      autoPromotionSeconds: 300
      scaleDownDelaySeconds: 30
